### ISSUE TITLE
Send screenshot to different conversation?

### ISSUE THREAD

**Issue by jazmaan** [polywock/ask-screenshot#1]
Is there a way to pick among previous Claude conversations as to where the screenshot should go?  It seems to be defaulting to starting a new conversation even if I have a previous conversation open.

**Comment by polywock** [comment]
There's a setting called Continue Chat in the options page. That should be enabled by default, and it continues old conversations without starting over. It's weird that it's not working for you. It seems to work fine for me. It only works if the previous conversation wasn't closed and is the same one that was opened by the extension initially.

**Comment by jazmaan** [comment]
Well that's the issue though -  "it only works if the previous conversation
wasn't closed AND IS THE SAME ONE THAT WAS OPENED BY THE EXTENSION
INTIALLY".     But I've got several previous conversations that I often
return to but which were NOT initially opened by the extension.  They were
created by me before I had the extension.   No way to input screenshots
into those?

**Comment by polywock** [comment]
I'm currently looking into adding support for old conversations. A little bit hesitant. Although, it could be useful in certain cases, it could also encourage bad practices (continuing old conversations eats up quota very quickly).

If possible for your case and if you run into quota issues, i would recommend trying to convert that old conversation into a template.

**Comment by jazmaan** [comment]
I put a lot of effort into fine-tuning different Claude personas by
resuming old conversations.  When they get too large,  I have Claude
summarize them down to 500 words and then input the summary into a new
conversation.   That works pretty well to get him to retain much of his
previous "training".  When I realized that  your extension doesn't work on
my old conversations I just used windows screenshot instead.

**Comment by polywock** [comment]
Hello. An update: I have updated the extension to allow for using previous conversations. The latest version has been updated on Chrome, but might take a week or so for Edge and Firefox. Let me know if you it doesn't work or you need help setting it up. 

Usage
1. In options page, enable Advanced mode. 
2. Under the newly visible Advanced section, there's an option to change the base path. By default, it's /chats, but you can change it to a specific conversation id by setting it like so. 

/chat/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx

**Comment by jazmaan** [comment]
Thanks!  A little kludgy in that you have to enter the char url in
advance.   Would be nicer if you could pick the conversation after taking
the screenshot.  But it works!  Thanks!
