### ISSUE TITLE
Image not appearing on ChatGTP after right click and screen capture

### ISSUE THREAD

**Issue by designguyz** [polywock/ask-screenshot#6]
Image no longer appearing on ChatGTP after right click and screen capture.

Was working on both my Chrome and Edge Browser previously.
Can you please investigate?
Thank you!

**Comment by polywock** [comment]
Hello. ChatGPT moved from Next.JS to Mixer so the extension had to be reworked. I've pushed the update but may take up to a week for approval. 

I assume you're the same person who emailed me. Let me know if that's not the case so I reply back to them as well.

**Comment by designguyz** [comment]
Hello,

Yes, it was me, same person. Thank you for recognizing the problem and giving me an update on the fix.

Have a good day.
Cesar


     On Thursday, September 12, 2024 at 03:03:03 AM MST, polywock ***@***.***> wrote:  
 
 


Hello. ChatGPT moved from Next.JS to Mixer so the extension had to be reworked. I've pushed the update but may take up to a week for approval.

I assume you're the same person who emailed me. Let me know if that's not the case so I reply back to them as well.

**Comment by polywock** [comment]
Thank you for alerting me about the issue.

**Comment by polywock** [comment]
Chrome update is live. Let me know if there's any issues.

**Comment by designguyz** [comment]
It's working now!

Thank you so much for fixing this.



     On Friday, September 13, 2024 at 12:19:52 AM MST, polywock ***@***.***> wrote:  
 
 


Chrome update is live. Let me know if there's any issues.
